version: '3'
services:
  productpage:
    build: ./bookinfo/src/productpage
    ports:
      - "9080:9080"
    volumes:
      - ./bookinfo/src/productpage:/app
    container_name: 30-productpage

  details:
    build: ./bookinfo/src/details
    ports:
      - "9081:9080"
    volumes:
      - ./bookinfo/src/details:/opt/microservices
    container_name: 30-details

  reviews:
    build: 
      context: ./bookinfo/src/reviews/reviews-wlpcfg
      dockerfile: Dockerfile.v1
    ports:
      - "9082:9080"
    volumes:
      - ./bookinfo/src/reviews/reviews-wlpcfg:/opt/microservices
    container_name: 30-reviews

  ratings:
    build: ./bookinfo/src/ratings
    ports:
      - "9083:9080"
    volumes:
      - ./bookinfo/src/ratings:/opt/microservices
    container_name: 30-ratings
